services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/Kernel.php'

  App\Infrastructure\RabbitMQ\ConnectionProvider:
    arguments:
      $host: '%env(AMQP_HOST)%'
      $port: '%env(AMQP_PORT)%'
      $login: '%env(AMQP_LOGIN)%'
      $password: '%env(AMQP_PASSWORD)%'

  App\Infrastructure\RabbitMQ\Producer:
    arguments:
      $exchange: 'events'